### ISSUE TITLE
`apko_tag`

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/terraform-publisher-apko#10]
We want to be able to tag an image with semver tags, based on the version of one of its constituent packages.

```
resource "apko_tag" "semver" {
  image_ref = apko_build.foo.image_ref  # this must be a digest
  package = "busybox"
}
```

Possibly this takes a new structured output of the `apko_build`, or at least keys off its [`sbom` output](https://registry.terraform.io/providers/chainguard-dev/apko/latest/docs/resources/build#read-only), determines the version of the specified package (failing if it doesn't have it), stems apart the sections and tags the image with `:1`, `:1.2`, `:1.2.3` and `:1.2.3-r4`.

This would live alongside an `oci_tag` tag resource to tag the image with something static like `:latest`.

This also needs to compose with something that applies `-dev` tags for variants, when we have that.

**Comment by mattmoor** [comment]
@imjasonh I think a data source for apko version tags that takes the `apko_config` and emits a list of tags might be good?

**Comment by imjasonh** [comment]
> @imjasonh I think a data source for apko version tags that takes the `apko_config` and emits a list of tags might be good?

Sure, and then that feeds an `oci_tag` with `for_each` for each of those?

We also need to handle the case where there's a `go:1.19.5-r5` and `go:1.20.4-r1` that needs to have a winner declared for which one is `go:1`. And it's not as easy as just picking the highest, since we'll probably have a `go:1.21.0-r0` that's a pre-release, which shouldn't be `go:1`.

```
data "apko_config" "go" {
  ...
}

data "apko_tags" "go" {
  config = apko_config.go.config
}

resource "oci_tag" "tag-go-but-not-1" {
  for_each = toset([for each in apko_tags.go.version_tags : each if each != '1' ]
}
```

**Comment by mattmoor** [comment]
Yeah, agree.  I would be curious to know if/how the current logic deals with this overlapping version problem.

**Comment by imjasonh** [comment]
https://github.com/chainguard-dev/terraform-provider-apko/pull/76
